name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  NODE_VERSION: '18.x' 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Service Account - Install dependencies, Run Lint, Runt Tests
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present
        working-directory: ./account
        
      - name: Service Product - Install dependencies, Run Lint, Runt Tests
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present
        working-directory: ./product

      - name: Service Finance - Install dependencies, Run Lint, Runt Tests
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present
        working-directory: ./finance

      - name: Service Order - Install dependencies, Run Lint, Runt Tests
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present
        working-directory: ./order

      - name: Service Invoice - Install dependencies, Run Lint, Runt Tests
        run: |
          npm install
          npm run lint --if-present
          npm run test --if-present
        working-directory: ./invoice
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
        