version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    networks:
      - compose-bridge
    volumes:
      - mongoecomm:/data/db

  redis:
    image: redis
    container_name: redis-blocklist
    ports:
      - 6379:6379
    networks:
      - compose-bridge
    volumes:
      - redisecomm:/data

  mysql:
    image: mysql
    restart: always
    container_name: mysql-ecomm
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - compose-bridge
    volumes:
      - mysqlecomm:/var/lib/mysql

  product:
    build: "./product"
    container_name: ecomm-product
    networks:
      - compose-bridge
    ports:
      - 3003:3003
    volumes:
      - ./product:/app-node

  account:
    build: "./account"
    container_name: ecomm-account
    networks:
      - compose-bridge
    ports:
      - 3002:3002
    volumes:
      - ./account:/app-node

  finance:
    build: "./finance"
    container_name: ecomm-finance
    networks:
      - compose-bridge
    ports:
      - 3004:3004
    volumes:
      - ./finance:/app-node    

  order:
    build: "./order"
    container_name: ecomm-order
    networks:
      - compose-bridge
    ports:
      - 3005:3005
    volumes:
      - ./order:/app-node
      
  invoice:
    build: "./invoice"
    container_name: ecomm-invoice
    networks:
      - compose-bridge
    ports:
      - 3006:3006
    volumes:
      - ./invoice:/app-node
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - compose-bridge      
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge
volumes:
  mongoecomm:
  mysqlecomm:
  kafkaecomm:
  redisecomm: {}
