name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  NODE_VERSION: '18.x' 
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm ci
        working-directory: accounts
        
      - name: Build app
        run: npm run build --if-present
        working-directory: accounts
        
      - name: Run tests
        run: npm run test --if-present
        working-directory: accounts
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .
        
